name: jarvisdgl-action

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pycodestyle pydocstyle codecov pytest-cov coverage
        python setup.py install
     
    - name: Lint 
      run: |
        pycodestyle --ignore E203,W503 --exclude=tests jarvisdgl
        pydocstyle --match-dir=core --match-dir=io --match-dir=io --match-dir=ai --match-dir=analysis --match-dir=db --match-dir=tasks --count jarvisdgl
        flake8 --ignore E203,W503 --exclude=tests --statistics --count --exit-zero jarvisdgl
    - name: Test with pytest
      run: |
        coverage run -m pytest
        coverage report -m
        codecov
